//Caso de prueba 4
POST http://localhost:3001/api/logout HTTP/1.1
Content-Type: application/json

{
    "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdlcnNvbiIsImlhdCI6MTcyNjE1MzU2MH0.nVDQAS5lcfoVQXRaBuMQAw6nKX1E1YWTfcU27zCW41s"
}
